name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Rename outputs
        run: cp app/build/outputs/apk/release/*.apk Iris.apk

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          files: |
            Iris.apk
            iris_control_termux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
